### ISSUE TITLE
Update suggestion Readme section

### ISSUE THREAD

**Issue by marxcom** [NorthScript/glixer#13]
This became an issue for me. I had to ```git add -A``` before committing. I think needs to be added on line 7 of cloning to existing repo.

**Comment by Brekmister** [comment]
to commit all changes you do `git commit -a`

if you want to commit specific files:
`git add file1`
`git add file2`
`git commit`

**Comment by Brekmister** [comment]
I do believe you read the command wrong. As I already mentioned, `git commit -a` stages and commits all changes. `-m "Your Message Here"` specifies the commit message. I specified the message so that people don't get confused with their terminals magically change into a text-editor that they don't understand.
